# Generated by Django 3.1 on 2020-09-03 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post1', '0003_auto_20200903_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post1',
            name='link',
        ),
    ]
