# Generated by Django 3.1 on 2020-09-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(default='https://127.0.0.1:8000/post', max_length=100),
        ),
    ]
