# Generated by Django 3.1 on 2020-09-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_coment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='name',
        ),
    ]
