# Generated by Django 3.1 on 2020-09-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_coment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='user',
        ),
        migrations.AddField(
            model_name='coment',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
            preserve_default=False,
        ),
    ]
